name: QualityCustomItems
version: '${project.version}'
main: me.zombie_striker.qualitycustomitems.QualityCustomItems
api-version: 1.19
authors: [ Zombie_Striker ]
description: A framework for adding custom items.
